name: retrofit_example
description: example_protobuf
version: 1.0.0+1
environment:
  sdk: ^3.10.0

dependencies:
  dio: ^5.9.0
  flutter:
    sdk: flutter
  http_parser: ^4.1.2
  json_annotation: ^4.9.0
  logger: ^2.5.0
  protobuf: ^6.0.0
  retrofit: any

dev_dependencies:
  build_runner: ^2.10.4
  json_serializable: ^6.11.2
  lints: any
  mock_web_server: ^5.0.0-nullsafety.1
  protoc_plugin: ^25.0.0
  retrofit_generator: any

dependency_overrides:
  retrofit:
    path: ../retrofit
  retrofit_generator:
    path: ../generator
