name: retrofit_generator
description: retrofit generator is an dio client generator using source_gen and inspired by Chopper and Retrofit.
homepage: https://mings.in/retrofit.dart/
repository: https://github.com/trevorwang/retrofit.dart/
topics:
  - api
  - http
  - rest
  - retrofit
  - codegen
version: 10.2.3
environment:
  sdk: '>=3.8.0 <4.0.0'

dependencies:
  analyzer: '>=8.4.1 <11.0.0'
  build: ^4.0.0
  built_collection: ^5.1.1
  code_builder: ^4.10.1
  dart_style: ^3.1.1
  dio: ^5.9.0
  lean_builder: ^0.1.6
  protobuf: ^6.0.0
  retrofit: ^4.9.2
  source_gen: ^4.0.0

dev_dependencies:
  coverage: any
  lints: any
  source_gen_test: ^1.3.2
  test: ^1.25.15
